### ISSUE TITLE
Add gifs to SSMS tips

### ISSUE THREAD

**Issue by ktaranov** [ktaranov/sqlserver-kit#137]
SSMS tips: https://rebrand.ly/gh-ssms-tips

 - [ ] Tip 13 [SQLCMD mode](https://rebrand.ly/gh-ssms-tips#13)
 - [ ] Tip 30 [Live Query Statistics](https://rebrand.ly/gh-ssms-tips#30)
 - [ ] Tip 36 [Import Flat File to SQL Wizard](https://rebrand.ly/gh-ssms-tips#36)

**Comment by ktaranov** [comment]
Move to road map
